api_platform:
    title: Hello API Platform
    version: 1.0.0
    collection:
    defaults:        
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        pagination_client_items_per_page_parameter_name: itemsPerPage
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
